apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-gatekeeper-operator
spec:
  complianceType: musthave
  remediationAction: inform
  severity: high
  subscription:
    channel: stable
    name: gatekeeper-operator-product
    namespace: openshift-operators
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: gatekeeper-operator-product.v3.19.0
  upgradeApproval: Automatic
  versions: null
---
apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  audit:
    logLevel: INFO
    replicas: 1
  mutatingWebhook: Disabled
  validatingWebhook: Enabled
  webhook:
    emitAdmissionEvents: Enabled
    logLevel: INFO
    replicas: 2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    control-plane: audit-controller
  namespace: openshift-gatekeeper-system
status:
  phase: Running
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    control-plane: controller-manager
  namespace: openshift-gatekeeper-system
status:
  phase: Running
