apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: OCBC Configuration Management
    policy.open-cluster-management.io/controls: CM-4 Cost Chargeback
    policy.open-cluster-management.io/description: Must give labels when creating namespace
    policy.open-cluster-management.io/standards: 
  name: dsta-admission-namespace
  namespace: dsta-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: templates.gatekeeper.sh/v1beta1
      kind: ConstraintTemplate
      metadata:
        name: k8srequiredlabels
      spec:
        crd:
          spec:
            names:
              kind: K8sRequiredLabels
            validation:
              openAPIV3Schema:
                properties:
                  labels:
                    items: string
                    type: array
        targets:
        - rego: |
            package k8srequiredlabels
            violation[{"msg": msg, "details": {"missing_labels": missing}}] {
              provided := {label | input.review.object.metadata.labels[label]}
              required := {label | label := input.parameters.labels[_]}
              missing := required - provided
              count(missing) > 0
              msg := sprintf("you must provide labels: %v", [missing])
            }
          target: admission.k8s.gatekeeper.sh
  - objectDefinition:
      apiVersion: constraints.gatekeeper.sh/v1beta1
      kind: K8sRequiredLabels
      metadata:
        name: ns-must-have-cost-center
      spec:
        enforcementAction: dryrun
        match:
          kinds:
          - apiGroups:
            - ""
            kinds:
            - Namespace
        parameters:
          labels:
          - cost-center
  remediationAction: enforce
